### ISSUE TITLE
Use a different finance API

### ISSUE THREAD

**Issue by premnirmal** [premnirmal/StockTicker#17]
yql finance is pretty unreliable, sometimes returns `null` for all fields in a quote

**Comment by sniperle** [comment]
After your update to the new API, nearly all of my stock positions "disappeared" (except GDAXI). If I try to read add them the app tells me, that it's already existing. 
Do you already know about this issue? If not, please write me what addition information you need. Thanks.

Oh, and another question, do you know why your app is no more updated on F-Droid ?

**Comment by premnirmal** [comment]
yes @sniperle I did notice that. It has been fixed in the latest version (`1.30.21`). The issue is a result of switching from yahoo finance to google finance. Not sure about F-droid, will look into it. As far is I know, the pure-floss version of the app was being built on F-droid

**Comment by sniperle** [comment]
Strange, for me nothing changed with .21, my stocks are still not shown.

**Comment by sniperle** [comment]
Tested .22. and .24. Still the same problem, nearly all stocks are "hidden". 
These two are shown: ^GDAXI, ^DJI
And e.g. these are not shown: XAUUSD=X, XAGUSD=X, EURUSD=X, DBXN.SG (and others)

**Comment by premnirmal** [comment]
if the google finance api returns an error then the stocks fetched from google don't show. *^GDAXI* shows because that's fetched from yahoo. working on a fix for that.

**Comment by premnirmal** [comment]
Using a new api - https://github.com/premnirmal/StockTicker/commit/5b5e9dce286b0ea5d66be2de182e05119070b82d
