### ISSUE TITLE
Notifications in weekend for Friday changes

### ISSUE THREAD

**Issue by hbhbhbhbhbhb** [premnirmal/StockTicker#178]
The app sends repeated daily notifications on Saturday and Sunday for stock movements from Friday

**Comment by premnirmal** [comment]
If you have set the app to update on Saturdays and Sundays then it will show the summary notifications on weekends.

**Comment by hbhbhbhbhbhb** [comment]
Saturday and Sunday are not enabled

**Comment by premnirmal** [comment]
Will look into it, thanks

**Comment by premnirmal** [comment]
Fixed in 081d173

**Comment by hbhbhbhbhbhb** [comment]
Still having issues with this after the fix @premnirmal 
This morning (Sunday) I got notifs for 2 stocks that moved on Friday, which I had already been notified about.

I only have mon-fri enabled. My timezone is New Zealand.

**Comment by premnirmal** [comment]
Found the bug, will update. Thanks for letting me know

**Comment by premnirmal** [comment]
Fixed in 317fe270076c725c7196385c3f697b306b690a77
