### ISSUE TITLE
OTC stocks failed to fetch

### ISSUE THREAD

**Issue by neffnet** [premnirmal/StockTicker#28]
All my OTC stocks have disappeared from the widget. If I again add a missing ticker, I get an error like "failed to fetch," and the ticker appears with price $0. Soon it disappears again. 

In previous version similar problem would happen sometimes. Tickers would disappear and adding them again gave error like "ticker already exists," and eventually the tickers and prices would return on their own.

**Comment by premnirmal** [comment]
Hi @neffnet . Can you tell me with which symbols you are receiving the "failed to fetch" errors?

**Comment by neffnet** [comment]
Hi Prem, thanks for this quick response. I can give you a partial list
right now: ACBFF TWMJF CNNRF SQRSF HYYDF TBQBF APHQF. These are all foreign
ADR tickers. I did not try reinstalling the widget but I will if you
suggest.

Thanks
spencer

**Comment by Spqr753** [comment]
I have the same issue.  It fails for ticker GBTC, for example.

**Comment by premnirmal** [comment]
Hi Spencer,

Can you try again? ACBFF TWMJF CNNRF SQRSF and APHQF should work now.
Also @Spqr753 GBTC should work now, please try again.

Made some fixes on the backend.

Prem.

**Comment by neffnet** [comment]
Confirmed, thank you very much!

**Comment by Spqr753** [comment]
Gbtc works, but still getting a failure RESCU, for example


_______________-Spqr753
-------- Original message --------From: Spencer Neff <notifications@github.com> Date: 29/04/2017  10:52  (GMT-05:00) To: premnirmal/StockTicker <StockTicker@noreply.github.com> Cc: Spqr753 <Spqr753@yahoo.com>, Mention <mention@noreply.github.com> Subject: Re: [premnirmal/StockTicker] OTC stocks failed to fetch (#28) 
Confirmed, thank you very much!

**Comment by premnirmal** [comment]
Give me a list of symbols that you are experiencing issues with and I'll
see what I can do with the server.

Thanks

**Comment by Spqr753** [comment]
Here's all the tickers I am trying to add:

 

	

IVW


IVE


IJT


IJS


EFA


EEM


FM


ZROZ


NRK


MNOIX


BWX


PCY


VWOB


ELD


VCLT


JNK


PICB


EMCB


TIP


LTPZ


WIP


DJP


DCMSX


GUNR


USCI


ARCIX


PHYS


QRHIX


QSPIX


QMHIX


PUTW


NUPIX


^PUT


BTCUSD=X


GBTC


RESCU


GWPH


WEED.TO


ACBFF


KSA


^VIX


^SKEW


SVXY

 

 

 

_____________

Spqr753

**Comment by Spqr753** [comment]
And thanks for your good work on this, best ticker app out there!

 

 

 

_____________

Spqr753

**Comment by premnirmal** [comment]
Thanks @Spqr753 . Can you try now? All the symbols you provided are now added to the server.

**Comment by Spqr753** [comment]
Seems to be working now.

Out of curiosity, what was the issue..you have to add the tickers
individually?

 

 

_____________

Spqr753

**Comment by neffnet** [comment]
Some that were broken work now, but I have two more: SPRWF QRSRF

**Comment by premnirmal** [comment]
Hi @neffnet , should be working now.

**Comment by premnirmal** [comment]
@Spqr753 Yes, the server just needs to be configured so that it fetches the quotes from the correct source. The default source doesn't serve quotes for all symbols, so special symbols like OTC quotes or some ETFs, mutual funds, international stocks, etc need to be configured
