### ISSUE TITLE
The application automatically crashes when I click on the end time option 

### ISSUE THREAD

**Issue by saraji-ali** [premnirmal/StockTicker#80]
# Project Information

* Repository: https://github.com/premnirmal/StockTicker
* Project Name: Stock Widget

# Expected behavior
The application should not crash when I click the end time option Rather, all end time options should be properly displayed

# Actual behavior

The application automatically crashes when I click on the end time option 

# How to reproduce

1-[Download ](https://play.google.com/store/apps/details?id=com.github.premnirmal.tickerwidget)the app and open it
2- Go to the setting
3- click on end time 
4- see bug
* Browser/App version:  Current Version 3.0.4
* Operating system: 6.0.1
* Smartphone: Galaxy j7 

# Recording Of The Bug

![20190507_145133](https://user-images.githubusercontent.com/50115498/57294173-adc26f80-707b-11e9-9722-ddeb73d6d7fc.gif)

# My Github Account
https://github.com/facebook-786

# Logcat

<pre><code>E/AndroidRuntime(11193): FATAL EXCEPTION: main

E/AndroidRuntime(11193): Process: com.github.premnirmal.tickerwidget, PID: 11193

E/AndroidRuntime(11193): android.view.InflateException: Binary XML file line #20: Error inflating class android.widget.TimePicker

E/AndroidRuntime(11193): 	at android.view.LayoutInflater.createView(LayoutInflater.java:633)

E/AndroidRuntime(11193): 	at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.onCreateView(SourceFile:164)

E/AndroidRuntime(11193): 	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682)

E/AndroidRuntime(11193): 	at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.onCreateView(SourceFile:148)

E/AndroidRuntime(11193): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)

E/AndroidRuntime(11193): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:482)

E/AndroidRuntime(11193): 	at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(SourceFile:60)

E/AndroidRuntime(11193): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)

E/AndroidRuntime(11193): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:365)

E/AndroidRuntime(11193): 	at android.app.TimePickerDialog.<init>(TimePickerDialog.java:134)

E/AndroidRuntime(11193): 	at android.app.TimePickerDialog.<init>(TimePickerDialog.java:102)

E/AndroidRuntime(11193): 	at com.github.premnirmal.ticker.settings.SettingsFragment.onDisplayPreferenceDialog(SourceFile:113)

E/AndroidRuntime(11193): 	at androidx.preference.PreferenceManager.showDialog(SourceFile:530)

E/AndroidRuntime(11193): 	at androidx.preference.DialogPreference.onClick(SourceFile:258)

E/AndroidRuntime(11193): 	at androidx.preference.Preference.performClick(SourceFile:1167)

E/AndroidRuntime(11193): 	at androidx.preference.Preference.performClick(SourceFile:1152)

E/AndroidRuntime(11193): 	at androidx.preference.Preference$1.onClick(SourceFile:182)

E/AndroidRuntime(11193): 	at android.view.View.performClick(View.java:5076)

E/AndroidRuntime(11193): 	at android.view.View$PerformClick.run(View.java:20279)

E/AndroidRuntime(11193): 	at android.os.Handler.handleCallback(Handler.java:739)

E/AndroidRuntime(11193): 	at android.os.Handler.dispatchMessage(Handler.java:95)

E/AndroidRuntime(11193): 	at android.os.Looper.loop(Looper.java:135)

E/AndroidRuntime(11193): 	at android.app.ActivityThread.main(ActivityThread.java:5910)

E/AndroidRuntime(11193): 	at java.lang.reflect.Method.invoke(Native Method)

E/AndroidRuntime(11193): 	at java.lang.reflect.Method.invoke(Method.java:372)

E/AndroidRuntime(11193): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)

E/AndroidRuntime(11193): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)

E/AndroidRuntime(11193): Caused by: java.lang.reflect.InvocationTargetException

E/AndroidRuntime(11193): 	at java.lang.reflect.Constructor.newInstance(Native Method)

E/AndroidRuntime(11193): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:288)

E/AndroidRuntime(11193): 	at android.view.LayoutInflater.createView(LayoutInflater.java:607)

E/AndroidRuntime(11193): 	... 26 more

E/AndroidRuntime(11193): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void android.widget.TimePicker$TimePickerDelegate.onRtlPropertiesChanged(int)' on a null object reference

E/AndroidRuntime(11193): 	at android.widget.TimePicker.onRtlPropertiesChanged(TimePicker.java:193)

E/AndroidRuntime(11193): 	at android.view.View.resolvePadding(View.java:13757)

E/AndroidRuntime(11193): 	at android.view.ViewGroup.resolvePadding(ViewGroup.java:6344)

E/AndroidRuntime(11193): 	at android.view.View.initializeScrollbarsInternal(View.java:4849)

E/AndroidRuntime(11193): 	at android.view.View.<init>(View.java:4278)

E/AndroidRuntime(11193): 	at android.view.ViewGroup.<init>(ViewGroup.java:503)

E/AndroidRuntime(11193): 	at android.widget.FrameLayout.<init>(FrameLayout.java:115)

E/AndroidRuntime(11193): 	at android.widget.TimePicker.<init>(TimePicker.java:84)

E/AndroidRuntime(11193): 	at android.widget.TimePicker.<init>(TimePicker.java:80)

E/AndroidRuntime(11193): 	at android.widget.TimePicker.<init>(TimePicker.java:76)

E/AndroidRuntime(11193): 	... 29 more
</code></pre>

**Comment by brandleesee** [comment]
This is also true for start time.

**Comment by brandleesee** [comment]
If I may elaborate on how critical this bug is; because I operate on a vastly different timezone, I stop receiving updates a couple of hours after the NYSE opens its trading sessions.

**Comment by premnirmal** [comment]
@brandleesee which version of android are you seeing this issue on?

**Comment by brandleesee** [comment]
Thanks for reaching. Android version is 6.0.1.

**Comment by premnirmal** [comment]
Ok, it seems like this issue is specific to Android 6.0.1 and maybe lower versions too. I'll look into it this weekend. Thank you

**Comment by premnirmal** [comment]
This is a bug with the os and cannot be fixed easily. Fixing this requires using a custom time picker which is not simple to create. Since this bug only occurs in Android 6.0.1 Samsung devices, it is not worth the effort to fix it. If you experience this bug then you should update the os on your phone

**Comment by brandleesee** [comment]
For your information, there are no available updates for the OS on this phone. What are you going to suggest next, to purchase another phone?

**Comment by premnirmal** [comment]
If you deem this bug fixable then you are welcome to open a PR to fix it

**Comment by premnirmal** [comment]
I opened a [PR](https://github.com/premnirmal/StockTicker/pull/108) as an attempt to fix this. Can you test to verify that it is fixed? The fix is launched as a beta **v3.5.4**

**Comment by brandleesee** [comment]
Signed to Beta channel and reinstalled. Problem persists - no changes. Furthermore, somehow, two seperate applications (Messenger Lite & Windy) had their icons removed. On uninstalling the widget and restarting phone, icons were back to normal.

**Comment by premnirmal** [comment]
What is the version of the app you're using?

The other issue is unrelated to this app

**Comment by brandleesee** [comment]
v.3.5.4.
also sent two feedback messages through built in reporting

screenshots follow

![Screenshot_20200104-181342](https://user-images.githubusercontent.com/12674437/71769211-59c79d80-2f1e-11ea-8ec6-ed59f378c591.png)
![Screenshot_20200104-181332](https://user-images.githubusercontent.com/12674437/71769212-5a603400-2f1e-11ea-9331-94df77247a95.png)

**Comment by premnirmal** [comment]
Thanks, I see the crash via analytics now. This helps get some info. Will fix

**Comment by premnirmal** [comment]
Updated - please try with **v3.5.5**

**Comment by brandleesee** [comment]
I confirm that in my case the issue is resolved.

Thank you very much.

![Screenshot_20200105-002320](https://user-images.githubusercontent.com/12674437/71772793-cc05a580-2f51-11ea-86e3-450acb3136cd.png)
![Screenshot_20200105-002128](https://user-images.githubusercontent.com/12674437/71772794-cc05a580-2f51-11ea-8a8b-1c12062e6d7e.png)
![Screenshot_20200105-002030](https://user-images.githubusercontent.com/12674437/71772795-cc9e3c00-2f51-11ea-821e-4cd4ecf91adf.png)

**Comment by brandleesee** [comment]
Thank you for the patches, appreciated.
